openapi: 3.1.0
info:
  title: Authentic Source API
  description: | 
    API expected by Wallet API from data providers
    Endpoints advertised by /.well-known/authentic-source endpoint are actual one, that are exposed by Authentic source
    Paths in documentation are illustrative

  version: 1.0.1
servers:
  - url: 'https://authentic-source.bankid.cz'
paths:
  /.well-known/authentic-source:
    get:
      summary: Get the credential authentic source
      description: >- 
        Returns defined endpoints for authentic source.
        Endpoints advertised by this endpoint are actual one, that are exposed by authetic source
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticSourceMetadata'

  /retrieve:
    post:
      summary: Retrieve credential authentic source
      description: Retrieve credential authentic source
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveResponse'
        '400':
          description: Bad request, client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized, invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden, access denied, in case of invalid audience
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /authorize:
    post:
      summary: Match and authorize user's data from Wallet
      description: >-
        Authorize user by matching theirs data to source data, to retrieve token to be used for obtaining credentials data sets via /retrieve endpoint. 
        Endpoint also may return credential identifiers for multiple different data sets.

      security:
        - BearerAuth: [ ]

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizeResponse'
        '400':
          description: Bad request, client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized, invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden, access denied, in case of invalid audience
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AuthenticSourceMetadata:
      type: object
      required:
        - authentic_source_url
        - retrieve_endpoint
      properties:
        authentic_source_url:
          type: string
          description: URL of the authentic source
          example: https://authentic.example.com
        retrieve_endpoint:
          type: string
          description: >-
            Endpoint to retrieve credential from authentic source
          example: https://authentic.example.com/retrieve
        authorize_endpoint:
          type: string
          description: >-
            Endpoint to authorize credential retrieval from authentic source, used for credential_identifiers
          example: https://authentic.example.com/authorize

    RetrieveResponse:
      type: object
      required:
        - attributes
      properties:
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/Attribute'

    AuthorizeResponse:
      type: object
      required:
        - authorization_token
      properties:
        authorization_token:
          type: string
          description: Token to be used for obtaining credentials data sets via /retrieve endpoint
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        credential_identifiers:
          type: array
          description: >-
            List of credential identifiers for multiple different data sets.
          items:
            type: string
          example: ['credential_identifier_1', 'credential_identifier_2']
    Attribute:
      type: object
      required:
        - attribute_name
        - attribute_value
      properties:
        attribute_name:
          type: string
          description: Name of the attribute
        attribute_value:
          anyOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
            - type: object
          description: Value of the attribute
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
        error_description:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

